# Generated by Django 5.2.3 on 2025-08-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=15)),
            ],
            options={
                'verbose_name': 'Kan Grubu',
                'verbose_name_plural': 'Kan Grupları',
                'db_table': 'blood_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
                'db_table': 'city_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Birim',
                'verbose_name_plural': 'Birimler',
                'db_table': 'department_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
                'db_table': 'district_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=15)),
            ],
            options={
                'verbose_name': 'Eğitim Durumu',
                'verbose_name_plural': 'Eğitim Durumları',
                'db_table': 'education_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255, verbose_name='Firma Adı')),
                ('create', models.DateField(blank=True, db_column='create_', null=True, verbose_name='Oluşturma Tarihi')),
                ('delete', models.DateTimeField(blank=True, db_column='delete_', null=True, verbose_name='Silinme Tarihi')),
                ('address', models.CharField(blank=True, db_column='address_', max_length=255, null=True, verbose_name='Adres')),
                ('telephone', models.CharField(blank=True, db_column='telephone_', max_length=255, null=True, verbose_name='Telefon')),
                ('fax', models.CharField(blank=True, db_column='fax_', max_length=255, null=True, verbose_name='Faks')),
                ('email', models.CharField(blank=True, db_column='email_', max_length=255, null=True, verbose_name='e-Posta')),
                ('type_firm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Firma Türü')),
                ('tax', models.CharField(blank=True, db_column='tax_', max_length=255, null=True, verbose_name='Vergi Numara')),
                ('web', models.CharField(blank=True, db_column='web_', max_length=255, null=True, verbose_name='İnternet Site')),
                ('sgk_sicil', models.CharField(blank=True, max_length=255, null=True, verbose_name='SGK Sicil No')),
                ('payment', models.CharField(blank=True, db_column='payment_', max_length=255, null=True, verbose_name='Ödeme Tipi')),
                ('ceo_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yetkili')),
                ('ceo_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yetkili e-Posta')),
                ('ceo_cell', models.CharField(blank=True, max_length=255, null=True, verbose_name='Yetkili Telefon')),
                ('logo_media', models.FileField(blank=True, null=True, upload_to='logo_firm/', verbose_name='Firma Logosu')),
                ('active', models.BooleanField(db_column='active_')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmalar',
                'db_table': 'firm_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
                ('short', models.CharField(blank=True, db_column='short_', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Dil',
                'verbose_name_plural': 'Diller',
                'db_table': 'language_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(blank=True, db_column='create_', null=True)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
                ('delete', models.DateTimeField(blank=True, db_column='delete_', null=True)),
                ('active', models.BooleanField(db_column='active_')),
            ],
            options={
                'verbose_name': 'Medya',
                'verbose_name_plural': 'Medyalar',
                'db_table': 'media_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Medya Türü',
                'verbose_name_plural': 'Medya Türleri',
                'db_table': 'media_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nace',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
                ('code', models.CharField(db_column='code_', max_length=15)),
                ('description', models.CharField(db_column='description_', max_length=511)),
            ],
            options={
                'verbose_name': 'NACE Kodu',
                'verbose_name_plural': 'NACE Kodları',
                'db_table': 'nace_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
            ],
            options={
                'verbose_name': 'Dizin Yolu',
                'verbose_name_plural': 'Dizin Yolları',
                'db_table': 'path_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True, verbose_name='Ad')),
                ('surname', models.CharField(blank=True, db_column='surname_', max_length=255, null=True, verbose_name='Soyad')),
                ('tckno', models.CharField(blank=True, db_column='tckno_', max_length=11, null=True, verbose_name='TC Kimlik Numara')),
                ('address', models.CharField(blank=True, db_column='address_', max_length=255, null=True, verbose_name='Adres')),
                ('cell', models.CharField(blank=True, db_column='cell_', max_length=15, null=True, verbose_name='Telefon')),
                ('birthday', models.DateTimeField(blank=True, db_column='birthday_', null=True, verbose_name='Doğum Tarihi')),
                ('driving_license', models.CharField(blank=True, max_length=15, null=True, verbose_name='Sürücü Belge')),
                ('status', models.CharField(blank=True, db_column='status_', max_length=255, null=True, verbose_name='Durum')),
                ('children', models.IntegerField(blank=True, db_column='children_', null=True, verbose_name='Çocuk Sayısı')),
                ('email', models.CharField(blank=True, db_column='email_', max_length=255, null=True, verbose_name='e-Posta')),
                ('military', models.BooleanField(choices=[(True, 'Yaptı/Muaf'), (False, 'Yapmadı')], db_column='military_', default=True, verbose_name='Askerlik Durumu')),
                ('gender', models.BooleanField(choices=[(True, 'Erkek'), (False, 'Kadın')], db_column='gender_', default=True, verbose_name='Cinsiyet')),
                ('marital', models.BooleanField(choices=[(True, 'Evli'), (False, 'Bekar')], db_column='marital_', default=False, verbose_name='Medeni Durum')),
                ('commencement', models.DateField(blank=True, db_column='commencement_', null=True, verbose_name='İşe Başlama Tarihi')),
                ('termination', models.DateField(blank=True, db_column='termination_', null=True, verbose_name='İşten Ayrılma Tarihi')),
                ('delete', models.DateTimeField(blank=True, db_column='delete_', null=True, verbose_name='Silinme Tarihi')),
                ('picture', models.FileField(blank=True, db_column='picture_', null=True, upload_to='picture_personnel/', verbose_name='Personel Resmi')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'db_table': 'personnel_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxOffice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
            ],
            options={
                'verbose_name': 'Vergi Daire',
                'verbose_name_plural': 'Vergi Daireleri',
                'db_table': 'tax_office',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='name_', max_length=255, null=True, verbose_name='Kullanıcı Adı')),
                ('tckno', models.CharField(blank=True, db_column='tckno_', max_length=11, null=True, verbose_name='TC Kimlik No')),
                ('certificate_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sertifika Numarası')),
                ('title', models.CharField(blank=True, db_column='title_', max_length=255, null=True, verbose_name='Unvan')),
                ('email', models.CharField(blank=True, db_column='email_', max_length=255, null=True, verbose_name='e-Posta')),
                ('pasword', models.CharField(blank=True, db_column='password_', max_length=32, null=True, verbose_name='Parola')),
                ('picture', models.FileField(blank=True, null=True, upload_to='picture_user/', verbose_name='Kullanıcı Resmi')),
                ('first_name', models.FileField(blank=True, db_column='first_name', max_length=255, null=True, upload_to='', verbose_name='Adı')),
                ('last_name', models.FileField(blank=True, db_column='last_name', max_length=255, null=True, upload_to='', verbose_name='Soyadı')),
                ('active', models.BooleanField(db_column='active_', default=True)),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'user_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFirm',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'firm_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('create', models.DateTimeField(db_column='create_')),
            ],
            options={
                'verbose_name': 'Kullanıcı-Firma Ataması',
                'verbose_name_plural': 'Kullanıcı-Firma Atamaları',
                'db_table': 'user_firm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name_', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='description_', max_length=511, null=True)),
            ],
            options={
                'verbose_name': 'Kullanıcı Grubu',
                'verbose_name_plural': 'Kullanıcı Grupları',
                'db_table': 'user_group',
                'managed': False,
            },
        ),
    ]
