# Generated by Django 5.2.3 on 2025-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Faktör Adı')),
                ('category', models.CharField(choices=[('KAPSAM_1', 'Kapsam 1'), ('KAPSAM_2', 'Kapsam 2'), ('KAPSAM_3', 'Kapsam 3'), ('KAPSAM_4', 'Kapsam 4'), ('KAPSAM_5', 'Kapsam 5'), ('KAPSAM_6', 'Kapsam 6')], max_length=50, verbose_name='Kategori/Kapsam')),
                ('value', models.FloatField(verbose_name='Değer (Katsayı)')),
                ('unit', models.CharField(max_length=50, verbose_name='Birim')),
                ('valid_from', models.DateField(verbose_name='Geçerlilik Başlangıcı')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Bitişi')),
            ],
            options={
                'verbose_name': 'Emisyon Faktörü',
                'verbose_name_plural': 'Emisyon Faktörleri',
                'ordering': ['-valid_from', 'name'],
            },
        ),
    ]
