# Generated by Django 5.2.3 on 2025-08-27 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoefficientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Katsayı Türü')),
                ('unit', models.CharField(max_length=50, verbose_name='Birim')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Katsayı Türü',
                'verbose_name_plural': 'Katsayı Türleri',
            },
        ),
        migrations.CreateModel(
            name='InputCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Girdi Kategorisi')),
                ('scope', models.CharField(choices=[('KAPSAM_1', 'Kapsam 1'), ('KAPSAM_2', 'Kapsam 2'), ('KAPSAM_3', 'Kapsam 3'), ('KAPSAM_4', 'Kapsam 4'), ('KAPSAM_5', 'Kapsam 5'), ('KAPSAM_6', 'Kapsam 6')], max_length=50, verbose_name='Kapsam')),
            ],
            options={
                'verbose_name': 'Girdi Kategorisi',
                'verbose_name_plural': 'Girdi Kategorileri',
            },
        ),
        migrations.RemoveField(
            model_name='emissionfactor',
            name='unit',
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kaynak'),
        ),
        migrations.AddField(
            model_name='emissionfactor',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carbon.coefficienttype', verbose_name='Katsayı Türü'),
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Değer (FV/Tüketim)')),
                ('unit', models.CharField(max_length=50, verbose_name='Birim')),
                ('period_start', models.DateField(verbose_name='Dönem Başlangıcı')),
                ('period_end', models.DateField(verbose_name='Dönem Bitişi')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lokasyon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.inputcategory', verbose_name='Kategori')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='Oluşturan Kullanıcı')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Karbon Girdi Verisi',
                'verbose_name_plural': 'Karbon Girdi Verileri',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Rapor Zaman Noktası')),
                ('total_co2e', models.FloatField(verbose_name='Toplam CO2e (ton)')),
                ('direct_ratio', models.FloatField(verbose_name='Doğrudan Emisyon Oranı (%)')),
                ('indirect_ratio', models.FloatField(verbose_name='Dolaylı Emisyon Oranı (%)')),
                ('json_details', models.JSONField(blank=True, null=True, verbose_name='Detaylı Hesaplamalar (JSON)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm', verbose_name='Firma')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='Oluşturan Kullanıcı')),
            ],
            options={
                'verbose_name': 'Karbon Raporu',
                'verbose_name_plural': 'Karbon Raporları',
                'ordering': ['-report_date'],
            },
        ),
    ]
