# Generated by Django 5.2.3 on 2025-08-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0002_coefficienttype_inputcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionfactor',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carbon.coefficienttype', verbose_name='Katsayı Türü'),
        ),
    ]
