# Generated by Django 5.2.3 on 2025-08-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0003_alter_emissionfactor_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coefficienttype',
            options={'permissions': [('view_management_carbon', 'Karbon Yönetim Görüntüleme Hakkı')], 'verbose_name': 'Katsayı Türü', 'verbose_name_plural': 'Katsayı Türleri'},
        ),
        migrations.AlterModelOptions(
            name='emissionfactor',
            options={'ordering': ['-valid_from', 'name'], 'permissions': [('view_management_carbon', 'Karbon Yönetim Görüntüleme Hakkı')], 'verbose_name': 'Emisyon Faktörü', 'verbose_name_plural': 'Emisyon Faktörleri'},
        ),
        migrations.AlterModelOptions(
            name='inputdata',
            options={'ordering': ['-period_start'], 'permissions': [('view_input_carbon', 'Karbon Girdi Verisi Görüntüleme Hakkı')], 'verbose_name': 'Karbon Girdi Verisi', 'verbose_name_plural': 'Karbon Girdi Verileri'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-report_date'], 'permissions': [('view_report_carbon', 'Karbon Rapor Görüntüleme Hakkı')], 'verbose_name': 'Karbon Raporu', 'verbose_name_plural': 'Karbon Raporları'},
        ),
    ]
