# Generated by Django 5.2.3 on 2025-08-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0004_alter_coefficienttype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissionfactor',
            options={'ordering': ['-valid_from', 'name'], 'permissions': [('can_manage_user_firm_access', 'Karbon için kullanıcı ve firma ilişkisi kurabilir'), ('view_management_carbon', 'Karbon Yönetim Görüntüleme Hakkı')], 'verbose_name': 'Emisyon Faktörü', 'verbose_name_plural': 'Emisyon Faktörleri'},
        ),
    ]
