# Generated by Django 5.2.3 on 2025-09-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0005_alter_emissionfactor_options'),
        ('carbon', '0005_enhanced_carbon_models'),
    ]

    operations = [
    ]
