# Generated by Django 5.2.3 on 2025-09-01 20:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0006_merge_20250901_2345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissionfactor',
            options={'ordering': ['-valid_from', 'category', 'name'], 'permissions': [('view_management_carbon', 'Karbon Yönetim Görüntüleme Hakkı')], 'verbose_name': 'Emisyon Faktörü', 'verbose_name_plural': 'Emisyon Faktörleri'},
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='category',
            field=models.CharField(choices=[('KAPSAM_1', 'Kapsam 1 - Doğrudan Emisyonlar'), ('KAPSAM_2', 'Kapsam 2 - Dolaylı Emisyonlar (Enerji)'), ('KAPSAM_3', 'Kapsam 3 - Dolaylı Emisyonlar (Ulaşım)'), ('KAPSAM_4', 'Kapsam 4 - Kullanılan Ürünler'), ('KAPSAM_5', 'Kapsam 5 - Üretilen Ürünler'), ('KAPSAM_6', 'Kapsam 6 - Diğer')], max_length=50, verbose_name='Kapsam'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 1, 20, 48, 24, 488963, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kaynak'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carbon.coefficienttype', verbose_name='Katsayı Türü'),
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2025, 9, 1, 20, 48, 50, 851812, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emissionfactor',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Değer'),
        ),
        migrations.AlterField(
            model_name='inputcategory',
            name='scope',
            field=models.CharField(choices=[('KAPSAM_1', 'Kapsam 1 - Doğrudan Emisyonlar'), ('KAPSAM_2', 'Kapsam 2 - Dolaylı Emisyonlar (Enerji)'), ('KAPSAM_3', 'Kapsam 3 - Dolaylı Emisyonlar (Ulaşım)'), ('KAPSAM_4', 'Kapsam 4 - Kullanılan Ürünler'), ('KAPSAM_5', 'Kapsam 5 - Üretilen Ürünler'), ('KAPSAM_6', 'Kapsam 6 - Diğer')], max_length=50, verbose_name='Kapsam'),
        ),
        migrations.AlterField(
            model_name='report',
            name='json_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Detaylı Hesaplamalar'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(verbose_name='Rapor Tarihi'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_period_end',
            field=models.DateField(default=datetime.datetime(2025, 9, 1, 20, 49, 5, 836831, tzinfo=datetime.timezone.utc), verbose_name='Rapor Dönemi Bitiş'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='report_period_start',
            field=models.DateField(default=datetime.datetime(2025, 9, 1, 20, 49, 17, 36210, tzinfo=datetime.timezone.utc), verbose_name='Rapor Dönemi Başlangıç'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='total_co2e',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Toplam CO2e (ton)'),
        ),
    ]
