# Generated by Django 5.2.3 on 2025-09-03 15:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0007_alter_emissionfactor_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GWPValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch4_gwp', models.DecimalField(decimal_places=2, default=Decimal('27.9'), max_digits=6, verbose_name='CH4 GWP Değeri')),
                ('n2o_gwp', models.DecimalField(decimal_places=2, default=Decimal('273'), max_digits=6, verbose_name='N2O GWP Değeri')),
                ('valid_from', models.DateField(verbose_name='Geçerlilik Başlangıcı')),
                ('source', models.CharField(default='IPCC AR5', max_length=100)),
            ],
            options={
                'verbose_name': 'GWP Değerleri',
                'verbose_name_plural': 'GWP Değerleri',
            },
        ),
        migrations.AddField(
            model_name='fueltype',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Yoğunluk (kg/m³ veya kg/L)'),
        ),
        migrations.AddField(
            model_name='fueltype',
            name='unit',
            field=models.CharField(default='m³', max_length=20, verbose_name='Birim'),
        ),
        migrations.CreateModel(
            name='ExcelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('month', models.IntegerField(verbose_name='Ay')),
                ('scope1_total', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='Kapsam 1 Toplam')),
                ('scope2_total', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='Kapsam 2 Toplam')),
                ('scope3_total', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='Kapsam 3 Toplam')),
                ('scope4_total', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='Kapsam 4 Toplam')),
                ('total_co2e', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='TOPLAM CO2e')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm')),
            ],
            options={
                'verbose_name': 'Excel Raporu',
                'verbose_name_plural': 'Excel Raporları',
            },
        ),
        migrations.CreateModel(
            name='Scope1Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='Lokasyon')),
                ('consumption_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tüketim Değeri (FV)')),
                ('co2_emission', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='CO2 Emisyonu (ton)')),
                ('ch4_emission', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='CH4 Emisyonu (ton)')),
                ('n2o_emission', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='N2O Emisyonu (ton)')),
                ('co2e_total', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='Toplam CO2e (ton)')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('month', models.IntegerField(verbose_name='Ay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carbon.fueltype')),
            ],
            options={
                'verbose_name': 'Kapsam 1 (Excel)',
                'verbose_name_plural': 'Kapsam 1 Verileri (Excel)',
            },
        ),
        migrations.CreateModel(
            name='Scope2Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=100, verbose_name='Tesis/Bölüm')),
                ('electricity_kwh', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Elektrik (kWh)')),
                ('electricity_mwh', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Elektrik (MWh)')),
                ('emission_factor', models.DecimalField(decimal_places=4, default=Decimal('0.442'), max_digits=10, verbose_name='EF (tCO2/MWh)')),
                ('co2e_total', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='Toplam CO2e (ton)')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('month', models.IntegerField(verbose_name='Ay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm')),
            ],
            options={
                'verbose_name': 'Kapsam 2 (Excel)',
                'verbose_name_plural': 'Kapsam 2 Verileri (Excel)',
            },
        ),
        migrations.CreateModel(
            name='Scope4Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, verbose_name='Malzeme Adı')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Miktar (kg)')),
                ('emission_factor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='EF (kgCO2e/kg)')),
                ('co2e_total', models.DecimalField(decimal_places=9, default=0, max_digits=15, verbose_name='Toplam CO2e (ton)')),
                ('year', models.IntegerField(verbose_name='Yıl')),
                ('month', models.IntegerField(verbose_name='Ay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm')),
            ],
            options={
                'verbose_name': 'Kapsam 4 (Excel)',
                'verbose_name_plural': 'Kapsam 4 Verileri (Excel)',
            },
        ),
    ]
