# Generated by Django 5.2.3 on 2025-09-11 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0008_gwpvalues_fueltype_density_fueltype_unit_excelreport_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('1', 'KAPSAM 1'), ('2', 'KAPSAM 2'), ('3', 'KAPSAM 3'), ('4', 'KAPSAM 4')], max_length=1, verbose_name='Kapsam')),
                ('subscope', models.CharField(choices=[('1.1', 'Kapsam 1.1'), ('1.2', 'Kapsam 1.2'), ('1.3', 'Kapsam 1.3'), ('1.4', 'Kapsam 1.4'), ('1.5', 'Kapsam 1.5'), ('2.1', 'Kapsam 2.1'), ('3.1', 'Kapsam 3.1'), ('3.2', 'Kapsam 3.2'), ('3.3', 'Kapsam 3.3'), ('3.4', 'Kapsam 3.4'), ('3.5', 'Kapsam 3.5'), ('4.1', 'Kapsam 4.1'), ('4.2', 'Kapsam 4.2'), ('4.3', 'Kapsam 4.3')], max_length=5, verbose_name='Alt Kapsam')),
                ('coefficient_type', models.CharField(choices=[('EF_CO2', 'EF (kgCO2/TJ)'), ('EF_CH4', 'EF (kgCH4/TJ)'), ('EF_N2O', 'EF (kgN2O/TJ)'), ('NKD', 'NKD (TJ/Gg)'), ('YOGUNLUK_KG_M3', 'Yoğunluk (kg/m³)'), ('YOGUNLUK_TON_LT', 'Yoğunluk (ton/lt)'), ('YOGUNLUK_KG_LT', 'Yoğunluk (kg/litre)'), ('EF_TCO2_MWH', 'EF tCO2 (tCO2/MWh)'), ('EF_KG_CO2_KG', 'EF (kgCO2/kg)'), ('EF_TCO2E_KG', 'EF (tCO2e/kg)'), ('EF_KG_CO2E_KWH', 'EF (kgCO2e/kWh)'), ('EF_KG_CO2E_M3', 'EF (kgCO2e/m³)'), ('EF_KG_CO2_TON', 'EF (kgCO2/ton)'), ('EF_KG_CO2_M3', 'EF (kgCO2/m³)')], max_length=20, verbose_name='Katsayı Türü')),
                ('name', models.CharField(default='Genel', max_length=100, verbose_name='İsim')),
                ('value', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Değer')),
                ('unit', models.CharField(max_length=50, verbose_name='Birim')),
                ('valid_from', models.DateField(verbose_name='Geçerlilik Başlangıcı')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Bitişi')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Kaynak (ör: IPCC, DEFRA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coefficients', to='core.user')),
            ],
            options={
                'verbose_name': 'Karbon Katsayısı',
                'verbose_name_plural': 'Karbon Katsayıları',
                'ordering': ['scope', 'subscope', 'coefficient_type', 'name', '-valid_from'],
                'unique_together': {('scope', 'subscope', 'coefficient_type', 'name', 'valid_from')},
            },
        ),
    ]
