# Generated by Django 5.2.3 on 2025-09-15 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0011_alter_carboncoefficient_coefficient_type'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(choices=[(1, 'Kapsam 1'), (2, 'Kapsam 2'), (3, 'Kapsam 3'), (4, 'Kapsam 4')])),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scope', 'code'],
                'unique_together': {('scope', 'code')},
            },
        ),
        migrations.CreateModel(
            name='DynamicCarbonInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('scope', models.IntegerField()),
                ('data', models.JSONField()),
                ('co2e_total', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm')),
                ('subscope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carbon.subscope')),
            ],
            options={
                'indexes': [models.Index(fields=['firm', 'datetime'], name='carbon_dyna_firm_id_2c7aa3_idx'), models.Index(fields=['scope', 'subscope'], name='carbon_dyna_scope_73c73b_idx')],
            },
        ),
    ]
