# Generated by Django 5.2.3 on 2025-09-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0012_subscope_dynamiccarboninput'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scope1data',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scope1data',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scope1data',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='scope1data',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='scope1excel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scope1excel',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='scope1excel',
            name='fuel_type',
        ),
        migrations.AlterUniqueTogether(
            name='scope2data',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scope2data',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scope2data',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='scope2excel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scope2excel',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='scope3data',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scope3data',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='scope3data',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='scope4data',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scope4data',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='scope4excel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scope4excel',
            name='firm',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Scope1Data',
        ),
        migrations.DeleteModel(
            name='Scope1Excel',
        ),
        migrations.DeleteModel(
            name='Scope2Data',
        ),
        migrations.DeleteModel(
            name='Scope2Excel',
        ),
        migrations.DeleteModel(
            name='Scope3Data',
        ),
        migrations.DeleteModel(
            name='Scope4Data',
        ),
        migrations.DeleteModel(
            name='Scope4Excel',
        ),
    ]
