# Generated by Django 5.2.3 on 2025-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0013_alter_scope1data_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carboncoefficient',
            name='coefficient_type',
            field=models.CharField(choices=[('EF_CO2', 'EF (kgCO2/TJ)'), ('EF_CH4', 'EF (kgCH4/TJ)'), ('EF_N2O', 'EF (kgN2O/TJ)'), ('NKD', 'NKD (TJ/Gg)'), ('YOGUNLUK_KG_M3', 'Yoğunluk (kg/m³)'), ('YOGUNLUK_TON_LT', 'Yoğunluk (ton/lt)'), ('YOGUNLUK_KG_LT', 'Yoğunluk (kg/lt)'), ('EF_TCO2_MWH', 'EF (tCO2/MWh)'), ('EF_KG_CO2_KG', 'EF (kgCO2/kg)'), ('EF_KG_CO2E_KWH', 'EF (kgCO2e/kWh)'), ('EF_KG_CO2E_M3', 'EF (kgCO2e/m³)'), ('EF_KG_CO2_TON', 'EF (kgCO2/ton)'), ('EF_KG_CO2_M3', 'EF (kgCO2/m³)'), ('EF_KG_CO2E_ODA', 'EF (kgCO2e/oda)')], max_length=20, verbose_name='Katsayı Türü'),
        ),
    ]
