# Generated by Django 5.2.3 on 2025-09-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carbon', '0015_alter_carboncoefficient_coefficient_type'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=200, verbose_name='Rapor Adı')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='Rapor Tarihi')),
                ('period_start', models.DateField(verbose_name='Dönem Başlangıcı')),
                ('period_end', models.DateField(verbose_name='Dönem Bitişi')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('COMPLETED', 'Tamamlandı'), ('APPROVED', 'Onaylandı')], default='DRAFT', max_length=20)),
                ('scope1_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kapsam 1 Toplam')),
                ('scope1_stationary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sabit Yanma')),
                ('scope1_mobile', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Mobil Yanma')),
                ('scope2_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kapsam 2 Toplam')),
                ('scope2_electricity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Elektrik')),
                ('scope3_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kapsam 3 Toplam')),
                ('scope4_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kapsam 4 Toplam')),
                ('total_co2e', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam CO2e')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karbon Raporu',
                'verbose_name_plural': 'Karbon Raporları',
                'ordering': ['-report_date'],
            },
        ),
        migrations.RemoveField(
            model_name='emissionfactor',
            name='type',
        ),
        migrations.RemoveField(
            model_name='inputdata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='inputdata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inputdata',
            name='firm',
        ),
        migrations.AlterModelOptions(
            name='dynamiccarboninput',
            options={'ordering': ['-datetime'], 'verbose_name': 'Karbon Verisi', 'verbose_name_plural': 'Karbon Verileri'},
        ),
        migrations.AlterModelOptions(
            name='excelreport',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Excel Raporu', 'verbose_name_plural': 'Excel Raporları'},
        ),
        migrations.AlterModelOptions(
            name='gwpvalues',
            options={'ordering': ['-valid_from'], 'verbose_name': 'GWP Değeri', 'verbose_name_plural': 'GWP Değerleri'},
        ),
        migrations.AlterModelOptions(
            name='subscope',
            options={'ordering': ['scope', 'code'], 'verbose_name': 'Alt Kapsam', 'verbose_name_plural': 'Alt Kapsamlar'},
        ),
        migrations.AlterUniqueTogether(
            name='carboncoefficient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='excelreport',
            unique_together={('firm', 'year', 'month')},
        ),
        migrations.AddField(
            model_name='excelreport',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='excelreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='excelreport',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='carboncoefficient',
            name='coefficient_type',
            field=models.CharField(choices=[('EF_CO2', 'CO2 Emisyon Faktörü'), ('EF_CH4', 'CH4 Emisyon Faktörü'), ('EF_N2O', 'N2O Emisyon Faktörü'), ('NKD', 'Net Kalorifik Değer'), ('YOGUNLUK_KG_M3', 'Yoğunluk (kg/m³)'), ('YOGUNLUK_KG_LT', 'Yoğunluk (kg/L)'), ('YOGUNLUK_TON_LT', 'Yoğunluk (ton/L)'), ('EF_TCO2_MWH', 'Emisyon Faktörü (tCO2/MWh)'), ('EF_KG_CO2E_ODA', 'Emisyon Faktörü (kgCO2e/oda.gece)'), ('EF_KG_CO2_KG', 'Emisyon Faktörü (kgCO2/kg)'), ('EF_TCO2E_KG', 'Emisyon Faktörü (tCO2e/kg)'), ('EF_KG_CO2E_KWH', 'Emisyon Faktörü (kgCO2e/kWh)'), ('EF_KG_CO2E_M3', 'Emisyon Faktörü (kgCO2e/m³)'), ('EF_KG_CO2_TON', 'Emisyon Faktörü (kgCO2/ton)'), ('EF_KG_CO2_M3', 'Emisyon Faktörü (kgCO2/m³)')], max_length=20, verbose_name='Katsayı Türü'),
        ),
        migrations.AlterField(
            model_name='carboncoefficient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='carboncoefficient',
            name='name',
            field=models.CharField(max_length=255, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='carboncoefficient',
            name='scope',
            field=models.CharField(choices=[('1', 'Kapsam 1'), ('2', 'Kapsam 2'), ('3', 'Kapsam 3'), ('4', 'Kapsam 4')], max_length=1, verbose_name='Kapsam'),
        ),
        migrations.AlterField(
            model_name='carboncoefficient',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kaynak'),
        ),
        migrations.AlterField(
            model_name='carboncoefficient',
            name='subscope',
            field=models.CharField(choices=[('1.1', '1.1 - Sabit Yanma'), ('1.2', '1.2 - Mobil Yanma'), ('1.3', '1.3 - Proses Emisyonları'), ('1.4', '1.4 - Kaçak Emisyonlar'), ('1.5', '1.5 - AFOLU'), ('2.1', '2.1 - Elektrik Tüketimi'), ('3.1', '3.1 - Satın Alınan Mal ve Hizmet Taşımacılığı'), ('3.2', '3.2 - Satılan Mal ve Hizmet Taşımacılığı'), ('3.3', '3.3 - Kiralanan Varlıklar'), ('3.4', '3.4 - İşe Gidiş Geliş'), ('3.5', '3.5 - İş Seyahatleri'), ('4.1', '4.1 - Satın Alınan Mal ve Hizmetler'), ('4.2', '4.2 - Sermaye Malları'), ('4.3', '4.3 - Atık')], max_length=3, verbose_name='Alt Kapsam'),
        ),
        migrations.AlterField(
            model_name='dynamiccarboninput',
            name='co2e_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Toplam CO2e'),
        ),
        migrations.AlterField(
            model_name='dynamiccarboninput',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='Oluşturan'),
        ),
        migrations.AlterField(
            model_name='dynamiccarboninput',
            name='data',
            field=models.JSONField(verbose_name='Veri'),
        ),
        migrations.AlterField(
            model_name='dynamiccarboninput',
            name='datetime',
            field=models.DateTimeField(verbose_name='Tarih/Zaman'),
        ),
        migrations.AlterField(
            model_name='dynamiccarboninput',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='dynamiccarboninput',
            name='scope',
            field=models.IntegerField(verbose_name='Kapsam'),
        ),
        migrations.AlterField(
            model_name='dynamiccarboninput',
            name='subscope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carbon.subscope', verbose_name='Alt Kapsam'),
        ),
        migrations.AlterField(
            model_name='excelreport',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='excelreport',
            name='month',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ay'),
        ),
        migrations.AlterField(
            model_name='excelreport',
            name='scope1_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Kapsam 1 Toplam'),
        ),
        migrations.AlterField(
            model_name='excelreport',
            name='scope2_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Kapsam 2 Toplam'),
        ),
        migrations.AlterField(
            model_name='excelreport',
            name='scope3_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Kapsam 3 Toplam'),
        ),
        migrations.AlterField(
            model_name='excelreport',
            name='scope4_total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='Kapsam 4 Toplam'),
        ),
        migrations.AlterField(
            model_name='excelreport',
            name='total_co2e',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15, verbose_name='TOPLAM CO2e'),
        ),
        migrations.AlterField(
            model_name='gwpvalues',
            name='source',
            field=models.CharField(default='IPCC AR5', max_length=100, verbose_name='Kaynak'),
        ),
        migrations.AddIndex(
            model_name='carboncoefficient',
            index=models.Index(fields=['scope', 'subscope'], name='carbon_carb_scope_d05077_idx'),
        ),
        migrations.AddIndex(
            model_name='carboncoefficient',
            index=models.Index(fields=['coefficient_type'], name='carbon_carb_coeffic_cd8ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='carboncoefficient',
            index=models.Index(fields=['valid_from', 'valid_to'], name='carbon_carb_valid_f_7b3f35_idx'),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='Oluşturan'),
        ),
        migrations.AddField(
            model_name='report',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.firm', verbose_name='Firma'),
        ),
        migrations.DeleteModel(
            name='CoefficientType',
        ),
        migrations.DeleteModel(
            name='EmissionFactor',
        ),
        migrations.DeleteModel(
            name='InputCategory',
        ),
        migrations.DeleteModel(
            name='InputData',
        ),
        migrations.RemoveField(
            model_name='excelreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='excelreport',
            name='created_by',
        ),
    ]
