--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-09-02 22:14:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5267 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 247 (class 1259 OID 25662)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO mydbuser;

--
-- TOC entry 246 (class 1259 OID 25661)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 25670)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO mydbuser;

--
-- TOC entry 248 (class 1259 OID 25669)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 25656)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO mydbuser;

--
-- TOC entry 244 (class 1259 OID 25655)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 25676)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO mydbuser;

--
-- TOC entry 253 (class 1259 OID 25684)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO mydbuser;

--
-- TOC entry 252 (class 1259 OID 25683)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 25675)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 25690)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO mydbuser;

--
-- TOC entry 254 (class 1259 OID 25689)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 262 (class 1259 OID 33845)
-- Name: blood_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blood_ (
    id bigint NOT NULL,
    name_ character varying(15) NOT NULL
);


ALTER TABLE public.blood_ OWNER TO postgres;

--
-- TOC entry 261 (class 1259 OID 33844)
-- Name: blood__id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.blood__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.blood__id_seq OWNER TO postgres;

--
-- TOC entry 5270 (class 0 OID 0)
-- Dependencies: 261
-- Name: blood__id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.blood__id_seq OWNED BY public.blood_.id;


--
-- TOC entry 270 (class 1259 OID 42094)
-- Name: carbon_coefficienttype; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_coefficienttype (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    unit character varying(50) NOT NULL,
    description text NOT NULL
);


ALTER TABLE public.carbon_coefficienttype OWNER TO mydbuser;

--
-- TOC entry 269 (class 1259 OID 42093)
-- Name: carbon_coefficienttype_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_coefficienttype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_coefficienttype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 268 (class 1259 OID 42088)
-- Name: carbon_emissionfactor; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_emissionfactor (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    category character varying(50) NOT NULL,
    value numeric(15,6) NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    source character varying(200) NOT NULL,
    type_id bigint NOT NULL,
    subcategory character varying(10) NOT NULL,
    unit character varying(50) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.carbon_emissionfactor OWNER TO mydbuser;

--
-- TOC entry 267 (class 1259 OID 42087)
-- Name: carbon_emissionfactor_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_emissionfactor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_emissionfactor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 279 (class 1259 OID 58472)
-- Name: carbon_fueltype; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_fueltype (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    category character varying(20) NOT NULL,
    ncv numeric(12,6) NOT NULL,
    ef_co2 numeric(12,4) NOT NULL,
    ef_ch4 numeric(12,4) NOT NULL,
    ef_n2o numeric(12,4) NOT NULL,
    valid_from date NOT NULL,
    valid_to date,
    source character varying(200) NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.carbon_fueltype OWNER TO mydbuser;

--
-- TOC entry 278 (class 1259 OID 58471)
-- Name: carbon_fueltype_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_fueltype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_fueltype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 272 (class 1259 OID 42102)
-- Name: carbon_inputcategory; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_inputcategory (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    scope character varying(50) NOT NULL
);


ALTER TABLE public.carbon_inputcategory OWNER TO mydbuser;

--
-- TOC entry 271 (class 1259 OID 42101)
-- Name: carbon_inputcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_inputcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_inputcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 42114)
-- Name: carbon_inputdata; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_inputdata (
    id bigint NOT NULL,
    value double precision NOT NULL,
    unit character varying(50) NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    location character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    created_by_id bigint,
    firm_id bigint NOT NULL
);


ALTER TABLE public.carbon_inputdata OWNER TO mydbuser;

--
-- TOC entry 273 (class 1259 OID 42113)
-- Name: carbon_inputdata_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_inputdata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_inputdata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 42120)
-- Name: carbon_report; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_report (
    id bigint NOT NULL,
    report_date date NOT NULL,
    total_co2e numeric(15,6) NOT NULL,
    direct_ratio double precision NOT NULL,
    indirect_ratio double precision NOT NULL,
    json_details jsonb,
    generated_at timestamp with time zone NOT NULL,
    firm_id bigint NOT NULL,
    generated_by_id bigint,
    scope1_total numeric(15,6) NOT NULL,
    scope2_total numeric(15,6) NOT NULL,
    scope3_total numeric(15,6) NOT NULL,
    scope4_total numeric(15,6) NOT NULL,
    scope5_total numeric(15,6) NOT NULL,
    scope6_total numeric(15,6) NOT NULL,
    report_period_start date NOT NULL,
    report_period_end date NOT NULL
);


ALTER TABLE public.carbon_report OWNER TO mydbuser;

--
-- TOC entry 275 (class 1259 OID 42119)
-- Name: carbon_report_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_report ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 281 (class 1259 OID 58482)
-- Name: carbon_scope1data; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_scope1data (
    id bigint NOT NULL,
    combustion_type character varying(20) NOT NULL,
    location character varying(100) NOT NULL,
    consumption_value numeric(15,3) NOT NULL,
    consumption_unit character varying(20) NOT NULL,
    period_year integer NOT NULL,
    period_month integer NOT NULL,
    co2_emission numeric(15,6),
    ch4_emission numeric(15,6),
    n2o_emission numeric(15,6),
    total_co2e numeric(15,6),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    firm_id bigint NOT NULL,
    fuel_type_id bigint NOT NULL
);


ALTER TABLE public.carbon_scope1data OWNER TO mydbuser;

--
-- TOC entry 280 (class 1259 OID 58481)
-- Name: carbon_scope1data_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_scope1data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_scope1data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 283 (class 1259 OID 58490)
-- Name: carbon_scope2data; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_scope2data (
    id bigint NOT NULL,
    location character varying(100) NOT NULL,
    electricity_kwh numeric(15,2) NOT NULL,
    grid_emission_factor numeric(10,6) NOT NULL,
    period_year integer NOT NULL,
    period_month integer NOT NULL,
    total_co2e numeric(15,6),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    firm_id bigint NOT NULL
);


ALTER TABLE public.carbon_scope2data OWNER TO mydbuser;

--
-- TOC entry 282 (class 1259 OID 58489)
-- Name: carbon_scope2data_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_scope2data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_scope2data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 285 (class 1259 OID 58498)
-- Name: carbon_scope3data; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_scope3data (
    id bigint NOT NULL,
    transport_type character varying(20) NOT NULL,
    transport_mode character varying(20) NOT NULL,
    vehicle_type character varying(100) NOT NULL,
    distance_km numeric(12,2),
    fuel_consumption_lt numeric(12,3),
    cargo_weight_ton numeric(12,3),
    period_year integer NOT NULL,
    period_month integer NOT NULL,
    total_co2e numeric(15,6),
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    firm_id bigint NOT NULL,
    fuel_type_id bigint
);


ALTER TABLE public.carbon_scope3data OWNER TO mydbuser;

--
-- TOC entry 284 (class 1259 OID 58497)
-- Name: carbon_scope3data_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_scope3data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_scope3data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 287 (class 1259 OID 58506)
-- Name: carbon_scope4data; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.carbon_scope4data (
    id bigint NOT NULL,
    product_category character varying(20) NOT NULL,
    product_name character varying(200) NOT NULL,
    supplier character varying(200) NOT NULL,
    quantity numeric(15,3) NOT NULL,
    unit character varying(20) NOT NULL,
    emission_factor numeric(10,6) NOT NULL,
    emission_factor_source character varying(200) NOT NULL,
    period_year integer NOT NULL,
    period_month integer NOT NULL,
    total_co2e numeric(15,6),
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    firm_id bigint NOT NULL
);


ALTER TABLE public.carbon_scope4data OWNER TO mydbuser;

--
-- TOC entry 286 (class 1259 OID 58505)
-- Name: carbon_scope4data_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.carbon_scope4data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carbon_scope4data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 25464)
-- Name: city_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.city_ (
    id bigint NOT NULL,
    name_ character varying(255) NOT NULL
);


ALTER TABLE public.city_ OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 25467)
-- Name: city_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.city_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.city_id_seq OWNER TO postgres;

--
-- TOC entry 5273 (class 0 OID 0)
-- Dependencies: 218
-- Name: city_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.city_id_seq OWNED BY public.city_.id;


--
-- TOC entry 264 (class 1259 OID 33857)
-- Name: department_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department_ (
    id bigint NOT NULL,
    firm_id bigint NOT NULL,
    name_ character varying(255)
);


ALTER TABLE public.department_ OWNER TO postgres;

--
-- TOC entry 263 (class 1259 OID 33856)
-- Name: department__id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.department__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.department__id_seq OWNER TO postgres;

--
-- TOC entry 5276 (class 0 OID 0)
-- Dependencies: 263
-- Name: department__id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.department__id_seq OWNED BY public.department_.id;


--
-- TOC entry 219 (class 1259 OID 25468)
-- Name: district_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.district_ (
    id bigint NOT NULL,
    name_ character varying(255) NOT NULL,
    city_id bigint NOT NULL
);


ALTER TABLE public.district_ OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 25471)
-- Name: district_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.district_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.district_id_seq OWNER TO postgres;

--
-- TOC entry 5279 (class 0 OID 0)
-- Dependencies: 220
-- Name: district_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.district_id_seq OWNED BY public.district_.id;


--
-- TOC entry 257 (class 1259 OID 25748)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO mydbuser;

--
-- TOC entry 256 (class 1259 OID 25747)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 25648)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO mydbuser;

--
-- TOC entry 242 (class 1259 OID 25647)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 25640)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO mydbuser;

--
-- TOC entry 240 (class 1259 OID 25639)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: mydbuser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 258 (class 1259 OID 25776)
-- Name: django_session; Type: TABLE; Schema: public; Owner: mydbuser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO mydbuser;

--
-- TOC entry 266 (class 1259 OID 33874)
-- Name: education_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.education_ (
    id bigint NOT NULL,
    name_ character varying(15) NOT NULL
);


ALTER TABLE public.education_ OWNER TO postgres;

--
-- TOC entry 265 (class 1259 OID 33873)
-- Name: education__id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.education__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.education__id_seq OWNER TO postgres;

--
-- TOC entry 5282 (class 0 OID 0)
-- Dependencies: 265
-- Name: education__id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.education__id_seq OWNED BY public.education_.id;


--
-- TOC entry 221 (class 1259 OID 25472)
-- Name: firm_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.firm_ (
    id bigint NOT NULL,
    name_ character varying(255) NOT NULL,
    city_id bigint,
    district_id bigint,
    tax_office_id bigint,
    nace_id bigint,
    create_ timestamp without time zone,
    delete_ timestamp without time zone,
    address_ character varying(255),
    telephone_ character varying(255),
    fax_ character varying(255),
    email_ character varying(255),
    type_firm character varying(255),
    tax_ character varying(255),
    web_ character varying(255),
    sgk_sicil character varying(255),
    payment_ character varying(255),
    ceo_name character varying(255),
    ceo_email character varying(255),
    ceo_cell character varying(255),
    active_ boolean DEFAULT true NOT NULL,
    logo_media character varying(255)
);


ALTER TABLE public.firm_ OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 25478)
-- Name: firm_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.firm_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.firm_id_seq OWNER TO postgres;

--
-- TOC entry 5285 (class 0 OID 0)
-- Dependencies: 222
-- Name: firm_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.firm_id_seq OWNED BY public.firm_.id;


--
-- TOC entry 223 (class 1259 OID 25479)
-- Name: language_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.language_ (
    id bigint NOT NULL,
    name_ character varying(255),
    short_ character varying(255)
);


ALTER TABLE public.language_ OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 25484)
-- Name: language__id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.language__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.language__id_seq OWNER TO postgres;

--
-- TOC entry 5288 (class 0 OID 0)
-- Dependencies: 224
-- Name: language__id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.language__id_seq OWNED BY public.language_.id;


--
-- TOC entry 225 (class 1259 OID 25485)
-- Name: media_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.media_ (
    id bigint NOT NULL,
    create_ timestamp without time zone,
    media_type_id bigint,
    path_id bigint,
    name_ character varying(255),
    delete_ timestamp without time zone,
    active_ boolean DEFAULT true NOT NULL
);


ALTER TABLE public.media_ OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 25489)
-- Name: media_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.media_id_seq OWNER TO postgres;

--
-- TOC entry 5291 (class 0 OID 0)
-- Dependencies: 226
-- Name: media_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.media_id_seq OWNED BY public.media_.id;


--
-- TOC entry 227 (class 1259 OID 25490)
-- Name: media_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.media_type (
    id bigint NOT NULL,
    name_ character varying(255)
);


ALTER TABLE public.media_type OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 25493)
-- Name: media_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.media_type_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.media_type_id_seq OWNER TO postgres;

--
-- TOC entry 5294 (class 0 OID 0)
-- Dependencies: 228
-- Name: media_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.media_type_id_seq OWNED BY public.media_type.id;


--
-- TOC entry 229 (class 1259 OID 25494)
-- Name: nace_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nace_ (
    id bigint NOT NULL,
    name_ character varying(255) NOT NULL,
    code_ character varying(15) NOT NULL,
    description_ character varying(511) NOT NULL
);


ALTER TABLE public.nace_ OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 25499)
-- Name: nace_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.nace_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.nace_id_seq OWNER TO postgres;

--
-- TOC entry 5297 (class 0 OID 0)
-- Dependencies: 230
-- Name: nace_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.nace_id_seq OWNED BY public.nace_.id;


--
-- TOC entry 231 (class 1259 OID 25500)
-- Name: path_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.path_ (
    id bigint NOT NULL,
    name_ character varying(255) NOT NULL
);


ALTER TABLE public.path_ OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 25503)
-- Name: path_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.path_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.path_id_seq OWNER TO postgres;

--
-- TOC entry 5300 (class 0 OID 0)
-- Dependencies: 232
-- Name: path_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.path_id_seq OWNED BY public.path_.id;


--
-- TOC entry 260 (class 1259 OID 33832)
-- Name: personnel_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.personnel_ (
    id bigint NOT NULL,
    name_ character varying(255),
    surname_ character varying(255),
    tckno_ character varying(11),
    address_ character varying(255),
    cell_ character varying(15),
    birthday_ timestamp without time zone,
    driving_license character varying(15),
    status_ character varying(255),
    education_id bigint,
    department_id bigint,
    children_ integer DEFAULT 0,
    email_ character varying(255),
    blood_id bigint,
    military_ boolean DEFAULT true NOT NULL,
    gender_ boolean DEFAULT true NOT NULL,
    marital_ boolean DEFAULT false NOT NULL,
    related_personnel_id bigint,
    firm_id bigint,
    commencement_ timestamp without time zone,
    termination_ timestamp without time zone,
    delete_ timestamp without time zone,
    picture_ character varying(255)
);


ALTER TABLE public.personnel_ OWNER TO postgres;

--
-- TOC entry 259 (class 1259 OID 33831)
-- Name: personnel__id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.personnel__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.personnel__id_seq OWNER TO postgres;

--
-- TOC entry 5303 (class 0 OID 0)
-- Dependencies: 259
-- Name: personnel__id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.personnel__id_seq OWNED BY public.personnel_.id;


--
-- TOC entry 233 (class 1259 OID 25504)
-- Name: tax_office; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tax_office (
    id bigint NOT NULL,
    name_ character varying(255) NOT NULL,
    city_id bigint NOT NULL,
    district_id bigint NOT NULL
);


ALTER TABLE public.tax_office OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 25507)
-- Name: tax_office_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.tax_office_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.tax_office_id_seq OWNER TO postgres;

--
-- TOC entry 5306 (class 0 OID 0)
-- Dependencies: 234
-- Name: tax_office_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.tax_office_id_seq OWNED BY public.tax_office.id;


--
-- TOC entry 235 (class 1259 OID 25508)
-- Name: user_; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_ (
    id bigint NOT NULL,
    user_group_id bigint NOT NULL,
    language_id bigint,
    name_ character varying(255),
    tckno_ character varying(11),
    certificate_number character varying(255),
    title_ character varying(255),
    email_ character varying(255),
    password_ character varying(128),
    active_ boolean DEFAULT true NOT NULL,
    picture character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    is_superuser boolean,
    is_staff boolean,
    last_login timestamp with time zone,
    date_joined timestamp with time zone,
    auth_user_id integer,
    logo_media bigint
);


ALTER TABLE public.user_ OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 25514)
-- Name: user__id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user__id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user__id_seq OWNER TO postgres;

--
-- TOC entry 5309 (class 0 OID 0)
-- Dependencies: 236
-- Name: user__id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user__id_seq OWNED BY public.user_.id;


--
-- TOC entry 237 (class 1259 OID 25515)
-- Name: user_firm; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_firm (
    user_id bigint NOT NULL,
    firm_id bigint NOT NULL,
    create_ timestamp without time zone DEFAULT now() NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.user_firm OWNER TO postgres;

--
-- TOC entry 277 (class 1259 OID 50279)
-- Name: user_firm_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_firm_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_firm_id_seq OWNER TO postgres;

--
-- TOC entry 5312 (class 0 OID 0)
-- Dependencies: 277
-- Name: user_firm_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_firm_id_seq OWNED BY public.user_firm.id;


--
-- TOC entry 238 (class 1259 OID 25519)
-- Name: user_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_group (
    id bigint NOT NULL,
    name_ character varying(255),
    description_ character varying(511)
);


ALTER TABLE public.user_group OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 25524)
-- Name: user_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.user_group_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.user_group_id_seq OWNER TO postgres;

--
-- TOC entry 5315 (class 0 OID 0)
-- Dependencies: 239
-- Name: user_group_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.user_group_id_seq OWNED BY public.user_group.id;


--
-- TOC entry 4939 (class 2604 OID 33848)
-- Name: blood_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blood_ ALTER COLUMN id SET DEFAULT nextval('public.blood__id_seq'::regclass);


--
-- TOC entry 4918 (class 2604 OID 25525)
-- Name: city_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.city_ ALTER COLUMN id SET DEFAULT nextval('public.city_id_seq'::regclass);


--
-- TOC entry 4940 (class 2604 OID 33860)
-- Name: department_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department_ ALTER COLUMN id SET DEFAULT nextval('public.department__id_seq'::regclass);


--
-- TOC entry 4919 (class 2604 OID 25526)
-- Name: district_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.district_ ALTER COLUMN id SET DEFAULT nextval('public.district_id_seq'::regclass);


--
-- TOC entry 4941 (class 2604 OID 33877)
-- Name: education_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education_ ALTER COLUMN id SET DEFAULT nextval('public.education__id_seq'::regclass);


--
-- TOC entry 4920 (class 2604 OID 25527)
-- Name: firm_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.firm_ ALTER COLUMN id SET DEFAULT nextval('public.firm_id_seq'::regclass);


--
-- TOC entry 4922 (class 2604 OID 25528)
-- Name: language_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language_ ALTER COLUMN id SET DEFAULT nextval('public.language__id_seq'::regclass);


--
-- TOC entry 4923 (class 2604 OID 25529)
-- Name: media_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media_ ALTER COLUMN id SET DEFAULT nextval('public.media_id_seq'::regclass);


--
-- TOC entry 4925 (class 2604 OID 25530)
-- Name: media_type id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media_type ALTER COLUMN id SET DEFAULT nextval('public.media_type_id_seq'::regclass);


--
-- TOC entry 4926 (class 2604 OID 25531)
-- Name: nace_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nace_ ALTER COLUMN id SET DEFAULT nextval('public.nace_id_seq'::regclass);


--
-- TOC entry 4927 (class 2604 OID 25532)
-- Name: path_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.path_ ALTER COLUMN id SET DEFAULT nextval('public.path_id_seq'::regclass);


--
-- TOC entry 4934 (class 2604 OID 33835)
-- Name: personnel_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personnel_ ALTER COLUMN id SET DEFAULT nextval('public.personnel__id_seq'::regclass);


--
-- TOC entry 4928 (class 2604 OID 25533)
-- Name: tax_office id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tax_office ALTER COLUMN id SET DEFAULT nextval('public.tax_office_id_seq'::regclass);


--
-- TOC entry 4929 (class 2604 OID 25534)
-- Name: user_ id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_ ALTER COLUMN id SET DEFAULT nextval('public.user__id_seq'::regclass);


--
-- TOC entry 4932 (class 2604 OID 50280)
-- Name: user_firm id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_firm ALTER COLUMN id SET DEFAULT nextval('public.user_firm_id_seq'::regclass);


--
-- TOC entry 4933 (class 2604 OID 25535)
-- Name: user_group id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_group ALTER COLUMN id SET DEFAULT nextval('public.user_group_id_seq'::regclass);


--
-- TOC entry 4986 (class 2606 OID 33904)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4991 (class 2606 OID 25705)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4994 (class 2606 OID 25674)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4988 (class 2606 OID 25666)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4981 (class 2606 OID 25696)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4983 (class 2606 OID 25660)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5002 (class 2606 OID 25688)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 5005 (class 2606 OID 25720)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4996 (class 2606 OID 25680)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5008 (class 2606 OID 25694)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5011 (class 2606 OID 25734)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4999 (class 2606 OID 25769)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 5023 (class 2606 OID 33850)
-- Name: blood_ blood__pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blood_
    ADD CONSTRAINT blood__pkey PRIMARY KEY (id);


--
-- TOC entry 5032 (class 2606 OID 42100)
-- Name: carbon_coefficienttype carbon_coefficienttype_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_coefficienttype
    ADD CONSTRAINT carbon_coefficienttype_pkey PRIMARY KEY (id);


--
-- TOC entry 5029 (class 2606 OID 42092)
-- Name: carbon_emissionfactor carbon_emissionfactor_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_emissionfactor
    ADD CONSTRAINT carbon_emissionfactor_pkey PRIMARY KEY (id);


--
-- TOC entry 5046 (class 2606 OID 58480)
-- Name: carbon_fueltype carbon_fueltype_code_key; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_fueltype
    ADD CONSTRAINT carbon_fueltype_code_key UNIQUE (code);


--
-- TOC entry 5048 (class 2606 OID 58478)
-- Name: carbon_fueltype carbon_fueltype_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_fueltype
    ADD CONSTRAINT carbon_fueltype_pkey PRIMARY KEY (id);


--
-- TOC entry 5034 (class 2606 OID 42106)
-- Name: carbon_inputcategory carbon_inputcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_inputcategory
    ADD CONSTRAINT carbon_inputcategory_pkey PRIMARY KEY (id);


--
-- TOC entry 5039 (class 2606 OID 42118)
-- Name: carbon_inputdata carbon_inputdata_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_inputdata
    ADD CONSTRAINT carbon_inputdata_pkey PRIMARY KEY (id);


--
-- TOC entry 5043 (class 2606 OID 42126)
-- Name: carbon_report carbon_report_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_report
    ADD CONSTRAINT carbon_report_pkey PRIMARY KEY (id);


--
-- TOC entry 5052 (class 2606 OID 58488)
-- Name: carbon_scope1data carbon_scope1data_firm_id_location_fuel_ty_ecc76665_uniq; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope1data
    ADD CONSTRAINT carbon_scope1data_firm_id_location_fuel_ty_ecc76665_uniq UNIQUE (firm_id, location, fuel_type_id, period_year, period_month);


--
-- TOC entry 5055 (class 2606 OID 58486)
-- Name: carbon_scope1data carbon_scope1data_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope1data
    ADD CONSTRAINT carbon_scope1data_pkey PRIMARY KEY (id);


--
-- TOC entry 5059 (class 2606 OID 58496)
-- Name: carbon_scope2data carbon_scope2data_firm_id_location_period__6068a7be_uniq; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope2data
    ADD CONSTRAINT carbon_scope2data_firm_id_location_period__6068a7be_uniq UNIQUE (firm_id, location, period_year, period_month);


--
-- TOC entry 5061 (class 2606 OID 58494)
-- Name: carbon_scope2data carbon_scope2data_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope2data
    ADD CONSTRAINT carbon_scope2data_pkey PRIMARY KEY (id);


--
-- TOC entry 5066 (class 2606 OID 58504)
-- Name: carbon_scope3data carbon_scope3data_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope3data
    ADD CONSTRAINT carbon_scope3data_pkey PRIMARY KEY (id);


--
-- TOC entry 5070 (class 2606 OID 58512)
-- Name: carbon_scope4data carbon_scope4data_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope4data
    ADD CONSTRAINT carbon_scope4data_pkey PRIMARY KEY (id);


--
-- TOC entry 4944 (class 2606 OID 25537)
-- Name: city_ city_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.city_
    ADD CONSTRAINT city_pkey PRIMARY KEY (id);


--
-- TOC entry 5025 (class 2606 OID 33862)
-- Name: department_ department__pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department_
    ADD CONSTRAINT department__pkey PRIMARY KEY (id);


--
-- TOC entry 4946 (class 2606 OID 25539)
-- Name: district_ district_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.district_
    ADD CONSTRAINT district_pkey PRIMARY KEY (id);


--
-- TOC entry 5014 (class 2606 OID 25755)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4976 (class 2606 OID 25654)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4978 (class 2606 OID 25652)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4974 (class 2606 OID 25646)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5018 (class 2606 OID 25782)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5027 (class 2606 OID 33879)
-- Name: education_ education__pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.education_
    ADD CONSTRAINT education__pkey PRIMARY KEY (id);


--
-- TOC entry 4948 (class 2606 OID 25541)
-- Name: firm_ firm_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.firm_
    ADD CONSTRAINT firm_pkey PRIMARY KEY (id);


--
-- TOC entry 4950 (class 2606 OID 25543)
-- Name: language_ language__pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.language_
    ADD CONSTRAINT language__pkey PRIMARY KEY (id);


--
-- TOC entry 4952 (class 2606 OID 25545)
-- Name: media_ media_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media_
    ADD CONSTRAINT media_pkey PRIMARY KEY (id);


--
-- TOC entry 4954 (class 2606 OID 25547)
-- Name: media_type media_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media_type
    ADD CONSTRAINT media_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4956 (class 2606 OID 25549)
-- Name: nace_ nace_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nace_
    ADD CONSTRAINT nace_pkey PRIMARY KEY (id);


--
-- TOC entry 4958 (class 2606 OID 25551)
-- Name: path_ path_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.path_
    ADD CONSTRAINT path_pkey PRIMARY KEY (id);


--
-- TOC entry 5021 (class 2606 OID 33843)
-- Name: personnel_ personnel__pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personnel_
    ADD CONSTRAINT personnel__pkey PRIMARY KEY (id);


--
-- TOC entry 4960 (class 2606 OID 25553)
-- Name: tax_office tax_office_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tax_office
    ADD CONSTRAINT tax_office_pkey PRIMARY KEY (id);


--
-- TOC entry 4962 (class 2606 OID 33896)
-- Name: user_ user__name__unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_
    ADD CONSTRAINT user__name__unique UNIQUE (name_);


--
-- TOC entry 4964 (class 2606 OID 25555)
-- Name: user_ user__pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_
    ADD CONSTRAINT user__pkey PRIMARY KEY (id);


--
-- TOC entry 4966 (class 2606 OID 33898)
-- Name: user_ user_email_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_
    ADD CONSTRAINT user_email_unique UNIQUE (email_);


--
-- TOC entry 4968 (class 2606 OID 50282)
-- Name: user_firm user_firm_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_firm
    ADD CONSTRAINT user_firm_pkey PRIMARY KEY (id);


--
-- TOC entry 4970 (class 2606 OID 50288)
-- Name: user_firm user_firm_user_id_firm_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_firm
    ADD CONSTRAINT user_firm_user_id_firm_id_key UNIQUE (user_id, firm_id);


--
-- TOC entry 4972 (class 2606 OID 25559)
-- Name: user_group user_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_group
    ADD CONSTRAINT user_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4984 (class 1259 OID 33905)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4989 (class 1259 OID 25716)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4992 (class 1259 OID 25717)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4979 (class 1259 OID 25702)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 5000 (class 1259 OID 25732)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 5003 (class 1259 OID 25731)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 5006 (class 1259 OID 25746)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5009 (class 1259 OID 25745)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4997 (class 1259 OID 25770)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 5030 (class 1259 OID 42127)
-- Name: carbon_emissionfactor_type_id_a32bd7ae; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_emissionfactor_type_id_a32bd7ae ON public.carbon_emissionfactor USING btree (type_id);


--
-- TOC entry 5044 (class 1259 OID 58526)
-- Name: carbon_fueltype_code_8e0d7605_like; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_fueltype_code_8e0d7605_like ON public.carbon_fueltype USING btree (code varchar_pattern_ops);


--
-- TOC entry 5035 (class 1259 OID 42143)
-- Name: carbon_inputdata_category_id_6bb8e8f6; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_inputdata_category_id_6bb8e8f6 ON public.carbon_inputdata USING btree (category_id);


--
-- TOC entry 5036 (class 1259 OID 42144)
-- Name: carbon_inputdata_created_by_id_14b04ed4; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_inputdata_created_by_id_14b04ed4 ON public.carbon_inputdata USING btree (created_by_id);


--
-- TOC entry 5037 (class 1259 OID 42145)
-- Name: carbon_inputdata_firm_id_774bfa42; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_inputdata_firm_id_774bfa42 ON public.carbon_inputdata USING btree (firm_id);


--
-- TOC entry 5040 (class 1259 OID 42156)
-- Name: carbon_report_firm_id_beccf16d; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_report_firm_id_beccf16d ON public.carbon_report USING btree (firm_id);


--
-- TOC entry 5041 (class 1259 OID 42157)
-- Name: carbon_report_generated_by_id_9ada771d; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_report_generated_by_id_9ada771d ON public.carbon_report USING btree (generated_by_id);


--
-- TOC entry 5049 (class 1259 OID 58542)
-- Name: carbon_scope1data_created_by_id_8b642030; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope1data_created_by_id_8b642030 ON public.carbon_scope1data USING btree (created_by_id);


--
-- TOC entry 5050 (class 1259 OID 58543)
-- Name: carbon_scope1data_firm_id_2ea6979f; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope1data_firm_id_2ea6979f ON public.carbon_scope1data USING btree (firm_id);


--
-- TOC entry 5053 (class 1259 OID 58544)
-- Name: carbon_scope1data_fuel_type_id_3c7c903e; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope1data_fuel_type_id_3c7c903e ON public.carbon_scope1data USING btree (fuel_type_id);


--
-- TOC entry 5056 (class 1259 OID 58555)
-- Name: carbon_scope2data_created_by_id_442983dd; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope2data_created_by_id_442983dd ON public.carbon_scope2data USING btree (created_by_id);


--
-- TOC entry 5057 (class 1259 OID 58556)
-- Name: carbon_scope2data_firm_id_477420be; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope2data_firm_id_477420be ON public.carbon_scope2data USING btree (firm_id);


--
-- TOC entry 5062 (class 1259 OID 58572)
-- Name: carbon_scope3data_created_by_id_bf211994; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope3data_created_by_id_bf211994 ON public.carbon_scope3data USING btree (created_by_id);


--
-- TOC entry 5063 (class 1259 OID 58573)
-- Name: carbon_scope3data_firm_id_37cb0c6d; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope3data_firm_id_37cb0c6d ON public.carbon_scope3data USING btree (firm_id);


--
-- TOC entry 5064 (class 1259 OID 58574)
-- Name: carbon_scope3data_fuel_type_id_b0c5c4fd; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope3data_fuel_type_id_b0c5c4fd ON public.carbon_scope3data USING btree (fuel_type_id);


--
-- TOC entry 5067 (class 1259 OID 58585)
-- Name: carbon_scope4data_created_by_id_67fd1f18; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope4data_created_by_id_67fd1f18 ON public.carbon_scope4data USING btree (created_by_id);


--
-- TOC entry 5068 (class 1259 OID 58586)
-- Name: carbon_scope4data_firm_id_14b44d71; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX carbon_scope4data_firm_id_14b44d71 ON public.carbon_scope4data USING btree (firm_id);


--
-- TOC entry 5012 (class 1259 OID 25766)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5015 (class 1259 OID 25767)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5016 (class 1259 OID 25784)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5019 (class 1259 OID 25783)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: mydbuser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5087 (class 2606 OID 25711)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5088 (class 2606 OID 25706)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5086 (class 2606 OID 25697)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5089 (class 2606 OID 25726)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5090 (class 2606 OID 25721)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5080 (class 2606 OID 33908)
-- Name: user_ auth_user_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_
    ADD CONSTRAINT auth_user_id_fk FOREIGN KEY (auth_user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5091 (class 2606 OID 25740)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5092 (class 2606 OID 25735)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5101 (class 2606 OID 58588)
-- Name: carbon_emissionfactor carbon_emissionfacto_type_id_a32bd7ae_fk_carbon_co; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_emissionfactor
    ADD CONSTRAINT carbon_emissionfacto_type_id_a32bd7ae_fk_carbon_co FOREIGN KEY (type_id) REFERENCES public.carbon_coefficienttype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5102 (class 2606 OID 42128)
-- Name: carbon_inputdata carbon_inputdata_category_id_6bb8e8f6_fk_carbon_in; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_inputdata
    ADD CONSTRAINT carbon_inputdata_category_id_6bb8e8f6_fk_carbon_in FOREIGN KEY (category_id) REFERENCES public.carbon_inputcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5103 (class 2606 OID 42133)
-- Name: carbon_inputdata carbon_inputdata_created_by_id_14b04ed4_fk_user__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_inputdata
    ADD CONSTRAINT carbon_inputdata_created_by_id_14b04ed4_fk_user__id FOREIGN KEY (created_by_id) REFERENCES public.user_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5104 (class 2606 OID 42138)
-- Name: carbon_inputdata carbon_inputdata_firm_id_774bfa42_fk_firm__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_inputdata
    ADD CONSTRAINT carbon_inputdata_firm_id_774bfa42_fk_firm__id FOREIGN KEY (firm_id) REFERENCES public.firm_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5105 (class 2606 OID 42146)
-- Name: carbon_report carbon_report_firm_id_beccf16d_fk_firm__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_report
    ADD CONSTRAINT carbon_report_firm_id_beccf16d_fk_firm__id FOREIGN KEY (firm_id) REFERENCES public.firm_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5106 (class 2606 OID 42151)
-- Name: carbon_report carbon_report_generated_by_id_9ada771d_fk_user__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_report
    ADD CONSTRAINT carbon_report_generated_by_id_9ada771d_fk_user__id FOREIGN KEY (generated_by_id) REFERENCES public.user_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5107 (class 2606 OID 58527)
-- Name: carbon_scope1data carbon_scope1data_created_by_id_8b642030_fk_user__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope1data
    ADD CONSTRAINT carbon_scope1data_created_by_id_8b642030_fk_user__id FOREIGN KEY (created_by_id) REFERENCES public.user_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5108 (class 2606 OID 58532)
-- Name: carbon_scope1data carbon_scope1data_firm_id_2ea6979f_fk_firm__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope1data
    ADD CONSTRAINT carbon_scope1data_firm_id_2ea6979f_fk_firm__id FOREIGN KEY (firm_id) REFERENCES public.firm_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5109 (class 2606 OID 58537)
-- Name: carbon_scope1data carbon_scope1data_fuel_type_id_3c7c903e_fk_carbon_fueltype_id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope1data
    ADD CONSTRAINT carbon_scope1data_fuel_type_id_3c7c903e_fk_carbon_fueltype_id FOREIGN KEY (fuel_type_id) REFERENCES public.carbon_fueltype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5110 (class 2606 OID 58545)
-- Name: carbon_scope2data carbon_scope2data_created_by_id_442983dd_fk_user__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope2data
    ADD CONSTRAINT carbon_scope2data_created_by_id_442983dd_fk_user__id FOREIGN KEY (created_by_id) REFERENCES public.user_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5111 (class 2606 OID 58550)
-- Name: carbon_scope2data carbon_scope2data_firm_id_477420be_fk_firm__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope2data
    ADD CONSTRAINT carbon_scope2data_firm_id_477420be_fk_firm__id FOREIGN KEY (firm_id) REFERENCES public.firm_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5112 (class 2606 OID 58557)
-- Name: carbon_scope3data carbon_scope3data_created_by_id_bf211994_fk_user__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope3data
    ADD CONSTRAINT carbon_scope3data_created_by_id_bf211994_fk_user__id FOREIGN KEY (created_by_id) REFERENCES public.user_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5113 (class 2606 OID 58562)
-- Name: carbon_scope3data carbon_scope3data_firm_id_37cb0c6d_fk_firm__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope3data
    ADD CONSTRAINT carbon_scope3data_firm_id_37cb0c6d_fk_firm__id FOREIGN KEY (firm_id) REFERENCES public.firm_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5114 (class 2606 OID 58567)
-- Name: carbon_scope3data carbon_scope3data_fuel_type_id_b0c5c4fd_fk_carbon_fueltype_id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope3data
    ADD CONSTRAINT carbon_scope3data_fuel_type_id_b0c5c4fd_fk_carbon_fueltype_id FOREIGN KEY (fuel_type_id) REFERENCES public.carbon_fueltype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5115 (class 2606 OID 58575)
-- Name: carbon_scope4data carbon_scope4data_created_by_id_67fd1f18_fk_user__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope4data
    ADD CONSTRAINT carbon_scope4data_created_by_id_67fd1f18_fk_user__id FOREIGN KEY (created_by_id) REFERENCES public.user_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5116 (class 2606 OID 58580)
-- Name: carbon_scope4data carbon_scope4data_firm_id_14b44d71_fk_firm__id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.carbon_scope4data
    ADD CONSTRAINT carbon_scope4data_firm_id_14b44d71_fk_firm__id FOREIGN KEY (firm_id) REFERENCES public.firm_(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5100 (class 2606 OID 33863)
-- Name: department_ department__firm_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.department_
    ADD CONSTRAINT department__firm_id_fkey FOREIGN KEY (firm_id) REFERENCES public.firm_(id);


--
-- TOC entry 5071 (class 2606 OID 25560)
-- Name: district_ district_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.district_
    ADD CONSTRAINT district_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.city_(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 5093 (class 2606 OID 25756)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5094 (class 2606 OID 25761)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: mydbuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5072 (class 2606 OID 25565)
-- Name: firm_ firm_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.firm_
    ADD CONSTRAINT firm_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.city_(id);


--
-- TOC entry 5073 (class 2606 OID 25570)
-- Name: firm_ firm_district_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.firm_
    ADD CONSTRAINT firm_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.district_(id);


--
-- TOC entry 5074 (class 2606 OID 25580)
-- Name: firm_ firm_nace_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.firm_
    ADD CONSTRAINT firm_nace_id_fkey FOREIGN KEY (nace_id) REFERENCES public.nace_(id);


--
-- TOC entry 5075 (class 2606 OID 25585)
-- Name: firm_ firm_tax_office_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.firm_
    ADD CONSTRAINT firm_tax_office_id_fkey FOREIGN KEY (tax_office_id) REFERENCES public.tax_office(id);


--
-- TOC entry 5076 (class 2606 OID 25590)
-- Name: media_ media_media_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media_
    ADD CONSTRAINT media_media_type_id_fkey FOREIGN KEY (media_type_id) REFERENCES public.media_type(id);


--
-- TOC entry 5077 (class 2606 OID 25595)
-- Name: media_ media_path_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.media_
    ADD CONSTRAINT media_path_id_fkey FOREIGN KEY (path_id) REFERENCES public.path_(id);


--
-- TOC entry 5095 (class 2606 OID 33851)
-- Name: personnel_ personnel__blood_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personnel_
    ADD CONSTRAINT personnel__blood_id_fkey FOREIGN KEY (blood_id) REFERENCES public.blood_(id) NOT VALID;


--
-- TOC entry 5096 (class 2606 OID 33868)
-- Name: personnel_ personnel__department_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personnel_
    ADD CONSTRAINT personnel__department_id_fkey FOREIGN KEY (department_id) REFERENCES public.department_(id) NOT VALID;


--
-- TOC entry 5097 (class 2606 OID 33880)
-- Name: personnel_ personnel__education_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personnel_
    ADD CONSTRAINT personnel__education_id_fkey FOREIGN KEY (education_id) REFERENCES public.education_(id) NOT VALID;


--
-- TOC entry 5098 (class 2606 OID 33890)
-- Name: personnel_ personnel__firm_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personnel_
    ADD CONSTRAINT personnel__firm_id_fkey FOREIGN KEY (firm_id) REFERENCES public.firm_(id) NOT VALID;


--
-- TOC entry 5099 (class 2606 OID 33885)
-- Name: personnel_ related_personnel_personnel__id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.personnel_
    ADD CONSTRAINT related_personnel_personnel__id_fkey FOREIGN KEY (related_personnel_id) REFERENCES public.personnel_(id) NOT VALID;


--
-- TOC entry 5078 (class 2606 OID 25600)
-- Name: tax_office tax_office_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tax_office
    ADD CONSTRAINT tax_office_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.city_(id);


--
-- TOC entry 5079 (class 2606 OID 25605)
-- Name: tax_office tax_office_district_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tax_office
    ADD CONSTRAINT tax_office_district_id_fkey FOREIGN KEY (district_id) REFERENCES public.district_(id);


--
-- TOC entry 5081 (class 2606 OID 25610)
-- Name: user_ user__language_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_
    ADD CONSTRAINT user__language_id_fkey FOREIGN KEY (language_id) REFERENCES public.language_(id);


--
-- TOC entry 5082 (class 2606 OID 33913)
-- Name: user_ user__logo_media_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_
    ADD CONSTRAINT user__logo_media_fkey FOREIGN KEY (logo_media) REFERENCES public.media_(id) NOT VALID;


--
-- TOC entry 5083 (class 2606 OID 25620)
-- Name: user_ user__user_group_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_
    ADD CONSTRAINT user__user_group_id_fkey FOREIGN KEY (user_group_id) REFERENCES public.user_group(id);


--
-- TOC entry 5084 (class 2606 OID 25625)
-- Name: user_firm user_firm_firm_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_firm
    ADD CONSTRAINT user_firm_firm_id_fkey FOREIGN KEY (firm_id) REFERENCES public.firm_(id) ON DELETE CASCADE;


--
-- TOC entry 5085 (class 2606 OID 25630)
-- Name: user_firm user_firm_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_firm
    ADD CONSTRAINT user_firm_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_(id) ON DELETE CASCADE;


--
-- TOC entry 5268 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO mydbuser;


--
-- TOC entry 5269 (class 0 OID 0)
-- Dependencies: 262
-- Name: TABLE blood_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.blood_ TO mydbuser;


--
-- TOC entry 5271 (class 0 OID 0)
-- Dependencies: 261
-- Name: SEQUENCE blood__id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.blood__id_seq TO mydbuser;


--
-- TOC entry 5272 (class 0 OID 0)
-- Dependencies: 217
-- Name: TABLE city_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.city_ TO mydbuser;


--
-- TOC entry 5274 (class 0 OID 0)
-- Dependencies: 218
-- Name: SEQUENCE city_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.city_id_seq TO mydbuser;


--
-- TOC entry 5275 (class 0 OID 0)
-- Dependencies: 264
-- Name: TABLE department_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.department_ TO mydbuser;


--
-- TOC entry 5277 (class 0 OID 0)
-- Dependencies: 263
-- Name: SEQUENCE department__id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.department__id_seq TO mydbuser;


--
-- TOC entry 5278 (class 0 OID 0)
-- Dependencies: 219
-- Name: TABLE district_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.district_ TO mydbuser;


--
-- TOC entry 5280 (class 0 OID 0)
-- Dependencies: 220
-- Name: SEQUENCE district_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.district_id_seq TO mydbuser;


--
-- TOC entry 5281 (class 0 OID 0)
-- Dependencies: 266
-- Name: TABLE education_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.education_ TO mydbuser;


--
-- TOC entry 5283 (class 0 OID 0)
-- Dependencies: 265
-- Name: SEQUENCE education__id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.education__id_seq TO mydbuser;


--
-- TOC entry 5284 (class 0 OID 0)
-- Dependencies: 221
-- Name: TABLE firm_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.firm_ TO mydbuser;


--
-- TOC entry 5286 (class 0 OID 0)
-- Dependencies: 222
-- Name: SEQUENCE firm_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.firm_id_seq TO mydbuser;


--
-- TOC entry 5287 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE language_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.language_ TO mydbuser;


--
-- TOC entry 5289 (class 0 OID 0)
-- Dependencies: 224
-- Name: SEQUENCE language__id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.language__id_seq TO mydbuser;


--
-- TOC entry 5290 (class 0 OID 0)
-- Dependencies: 225
-- Name: TABLE media_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.media_ TO mydbuser;


--
-- TOC entry 5292 (class 0 OID 0)
-- Dependencies: 226
-- Name: SEQUENCE media_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.media_id_seq TO mydbuser;


--
-- TOC entry 5293 (class 0 OID 0)
-- Dependencies: 227
-- Name: TABLE media_type; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.media_type TO mydbuser;


--
-- TOC entry 5295 (class 0 OID 0)
-- Dependencies: 228
-- Name: SEQUENCE media_type_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.media_type_id_seq TO mydbuser;


--
-- TOC entry 5296 (class 0 OID 0)
-- Dependencies: 229
-- Name: TABLE nace_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.nace_ TO mydbuser;


--
-- TOC entry 5298 (class 0 OID 0)
-- Dependencies: 230
-- Name: SEQUENCE nace_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.nace_id_seq TO mydbuser;


--
-- TOC entry 5299 (class 0 OID 0)
-- Dependencies: 231
-- Name: TABLE path_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.path_ TO mydbuser;


--
-- TOC entry 5301 (class 0 OID 0)
-- Dependencies: 232
-- Name: SEQUENCE path_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.path_id_seq TO mydbuser;


--
-- TOC entry 5302 (class 0 OID 0)
-- Dependencies: 260
-- Name: TABLE personnel_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.personnel_ TO mydbuser;


--
-- TOC entry 5304 (class 0 OID 0)
-- Dependencies: 259
-- Name: SEQUENCE personnel__id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.personnel__id_seq TO mydbuser;


--
-- TOC entry 5305 (class 0 OID 0)
-- Dependencies: 233
-- Name: TABLE tax_office; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.tax_office TO mydbuser;


--
-- TOC entry 5307 (class 0 OID 0)
-- Dependencies: 234
-- Name: SEQUENCE tax_office_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.tax_office_id_seq TO mydbuser;


--
-- TOC entry 5308 (class 0 OID 0)
-- Dependencies: 235
-- Name: TABLE user_; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.user_ TO mydbuser;


--
-- TOC entry 5310 (class 0 OID 0)
-- Dependencies: 236
-- Name: SEQUENCE user__id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.user__id_seq TO mydbuser;


--
-- TOC entry 5311 (class 0 OID 0)
-- Dependencies: 237
-- Name: TABLE user_firm; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.user_firm TO mydbuser;


--
-- TOC entry 5313 (class 0 OID 0)
-- Dependencies: 277
-- Name: SEQUENCE user_firm_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.user_firm_id_seq TO mydbuser;


--
-- TOC entry 5314 (class 0 OID 0)
-- Dependencies: 238
-- Name: TABLE user_group; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.user_group TO mydbuser;


--
-- TOC entry 5316 (class 0 OID 0)
-- Dependencies: 239
-- Name: SEQUENCE user_group_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.user_group_id_seq TO mydbuser;


--
-- TOC entry 2219 (class 826 OID 25638)
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON SEQUENCES TO mydbuser;


--
-- TOC entry 2218 (class 826 OID 25637)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public GRANT ALL ON TABLES TO mydbuser;


-- Completed on 2025-09-02 22:14:44

--
-- PostgreSQL database dump complete
--

